apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s # Check the app every 5 seconds
    scrape_configs:
      - job_name: 'heliosgrid-telemetry'
        static_configs:
          - targets: ['heliosgrid-service:8080']